# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isolation_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14isolation_info.proto\x12\tnet.proto\"\xcb\x01\n\rIsolationInfo\x12\x14\n\x0crequest_type\x18\x01 \x01(\x05\x12\x18\n\x10top_frame_origin\x18\x02 \x01(\t\x12\x14\n\x0c\x66rame_origin\x18\x03 \x01(\t\x12\x18\n\x10site_for_cookies\x18\x04 \x01(\t\x12<\n\rparty_context\x18\x05 \x01(\x0b\x32%.net.proto.IsolationInfo.PartyContext\x1a\x1c\n\x0cPartyContext\x12\x0c\n\x04site\x18\x01 \x03(\tB\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'isolation_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _ISOLATIONINFO._serialized_start=36
  _ISOLATIONINFO._serialized_end=239
  _ISOLATIONINFO_PARTYCONTEXT._serialized_start=211
  _ISOLATIONINFO_PARTYCONTEXT._serialized_end=239
# @@protoc_insertion_point(module_scope)
