# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network_id_proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16network_id_proto.proto\x12\x10net.nqe.internal\"N\n\x0eNetworkIDProto\x12\x17\n\x0f\x63onnection_type\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\t\x12\x17\n\x0fsignal_strength\x18\x03 \x01(\x05\x42\x02H\x03')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'network_id_proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _NETWORKIDPROTO._serialized_start=44
  _NETWORKIDPROTO._serialized_end=122
# @@protoc_insertion_point(module_scope)
